### ISSUE TITLE
It is possible to touch track and set value?

### ISSUE THREAD

**Issue by Micjoyce** [jeanregisser/react-native-slider#56] opened 2017-01-06 15:19 UTC

**Comment by gyzerok** [comment] 2017-02-02 13:09
Yeah, I am interested as well since it seem to be expected behaviour on Andorid

**Comment by asgvard** [comment] 2017-03-08 16:10
Would be nice to have, I'm using this package for video progress slider, and didn't found a good way on setting value just by touching the track, w/o actual sliding.

**Comment by asgvard** [comment] 2017-03-08 16:12
And seems like duplicate of #45 ?

**Comment by CaffGeek** [comment] 2017-07-31 21:11
Same.

**Comment by LEEY19** [comment] 2017-10-22 04:06
anyone has any progress on this? I am looking to set value by touching track as well

**Closed** 2018-01-04 14:18 UTC
