### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by PhilippKrone** [jeanregisser/react-native-slider#5] opened 2015-10-22 10:00 UTC
Hi @jeanregisser 

on Android, react-native-slider is currently not working for me (the slider is just not moving when dragging). After debugging, it seems to be due to _thumbHitTest returning "false" all the time. Could this be connected to https://github.com/facebook/react-native/pull/3426? My only idea is to have an "if Platform.OS === android return true" until this PR is merged - do you have a better idea? :)

Regards
Philipp

**Comment by jeanregisser** [comment] 2015-10-22 13:44
Hi @PhilippKrone,

Good finding!
It definitely looks like it's caused by the issue you linked.
What you're proposing seems good until the fix is merged (although it changes the behavior and allows moving the thumb even if your finger is not on it). 
Do you mind sending a PR here?

Anyway glad seeing people trying it on Android!
Thanks!

**Comment by jeanregisser** [comment] 2015-10-22 14:10
Alright, 0.4.0 with your fix has been published on NPM.
Thanks again @PhilippKrone!

**Closed by jeanregisser** 2015-10-22 14:10 UTC
